project:
  type: website
  output-dir: docs

website:
  title: "Michelle Hunn"
  navbar:
    background: primary
    search: true
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/mhunn/
      - icon: github
        href: https://github.com/mishelly-h
    left:
      - href: index.qmd
        text: Home
      - href: pages/about.qmd
        text: About Me
      - href: pages/projects.qmd
        text: Projects
  page-footer: 
    left: "Copyright 2024, Michelle Hunn" 

format:
  html:
    theme: lux 
    css: styles.css
    toc: true