---
title: "Projects"
---

**Master Thesis (submission October 2023):** Human Activity Recognition From
Wearable Sensor Data Using Supervised Machine Learning Algorithms

This thesis aims at providing a proof of concept for a larger project exploring child development and is situated within the realm of Human Activity Recognition (HAR). The focus lies on the recognition of ten distinct activities identified as pertinent to understand the daily life of children. The activities are: Walk, Run, Jump, Lie, Stand, Sit & Listen, Sit & Write, Sit & Read, Sit & Computer, Sit & Conversation. An experimental design was crafted, encompassing a sample of six participants, yielding nearly 12 hours of sensor data. The experimental setup incorporated Inertial Measurement Unit (IMU) sensors and proximity sensors, both operating at a sampling frequency of 45 Hz. After the labelling and pre-preocessing, the data set comprises 1,231,213 rows of data. Subsequently, two Machine Learning (ML) models were built and trained on this data set to classify the activities. One model is based on the LeNet architecture and the other employs a Recurrent Neural Network (RNN) equipped with Gated Recurrent Unit (GRU) layers. The LeNet-based model demonstrated a classification accuracy of 98.5%, while the GRU model achieved an accuracy of 88.1%. This thesis provides valuable insights by assessing the detectability of similar activities by exploring different neural network architectures for human activity detection tasks.


**Bachelor Thesis (submission August 2021):** An Empirical Study to examine the Relationship between a Leader’s Machiavellianism and the Followers’ pro-Group unethical behaviour

The present thesis was written as part of the bachelor’s programme at the University of Zurich (UZH) and serves the author to obtain the Bachelor of Arts UZH in Business and Economics. An empirical study was conducted to analyse the relationship between the leader’s Machiavellianism and the followers’ pro-group unethical behaviour. It was further investigated whether conscientiousness of the followers moderates this relationship. Using regression analysis, the hypotheses have been tested and no support was found for either hypothesis. The results are discussed and recommendations for improving the experiment are made.
