---
title: "Projects"
---

## Technical Projects


#### Dash Dashboard: Happiness Dashboard
The dashboard visually represents the global happiness score as well as the happiness scores of various countries and regions. The World Happiness Tracker App is designed to make the analysis of global happiness accessible and interactive. With this tool, you can compare happiness scores and discover trends. 

<div class="buttons">
[Deployed Happiness Dashboard](https://dsci-532-2024-3-world-happiness-tracker.onrender.com/)\
(page may take a while to load)
</div>



#### Python Package: passwordler
The passwordler package provides password management tools in Python. The package consists of four functions: generate_password, password_strength, encrypt_password, and decrypt_password. With key functionalities consolidated in one package, users can effortlessly generate strong passwords, evaluate their strength, and grasp encryption and decryption methods through our straightforward substitution cipher.

<div class="buttons">
[passwordler on readthedocs](https://passwordler.readthedocs.io/en/latest/?badge=latest)
</div>



#### Shiny Dashboard: SnoWatch
This dashboard focuses on visualizing snow measurements from different locations in Switzerland. The app allows users to put observations into context. This allows to recognize extreme observations as well as trends. 

<div class="buttons">
[SnoWatch on Github](https://github.com/mishelly-h/Snow-Switzerland)
</div>



#### Workflow practice: Speed Dating Analysis
This project delves into the dynamics of self-perceived attractiveness in the context of dating. We explored whether individuals accurately gauge their own appeal compared to external judgments. Analyzing data from speed dating studies, the findings reveal a systematic tendency for individuals to overestimate their attractiveness. While a significant correlation exists between self-ratings and others' ratings, this research underscores the interplay between self-perception and external judgments in the realm of dating. The implications range from improved self-esteem for those perceiving themselves as more attractive to potential challenges in social interactions. Future research could investigate the influence of contemporary factors like social media on self-perception and exploring the multidimensional aspects of attractiveness.

<div class="buttons">
[Speed Dating Analysis on Github](https://github.com/UBC-MDS/speed_dating_analysis)
</div>



## Thesis

#### Master Thesis: Human Activity Recognition From Wearable Sensor Data Using Supervised Machine Learning Algorithms
My thesis aimed at providing a proof of concept for a larger project exploring child development and is situated within the realm of Human Activity Recognition (HAR). First, I chose activities that I considered relevant for the given context. What are activities that a child does every day? And how can I break down complex activities into simple activities? I came to the conclusion that I could capture a large portion of daily activities with 10 activities: Walk, Run, Jump, Lie, Stand, Sit & Listen, Sit & Write, Sit & Read, Sit & Computer and Sit & Conversation.

Next, I designed an experiment to collect the data needed. The experimental setup incorporated Inertial Measurement Unit (IMU) sensors and proximity sensors, both operating at a sampling frequency of 45 Hz. In order to being able to collect the proximity data, each experiment round was performed in groups of two. In total, six participants participated in the experiment, yielding nearly 12 hours of sensor data. After the labelling and pre-preocessing, the data set comprised 1,231,213 rows of data. 

Then, I built and trined two Machine Learning (ML) models on this data set to classify the activities. One model is based on the LeNet architecture and the other employs a Recurrent Neural Network (RNN) with Gated Recurrent Unit (GRU) layers. The LeNet-based model achieved a classification accuracy of 98.5%, while the GRU model achieved an accuracy of 88.1%. 

Limitations such as the small sample size of six participants and limited computational power were acknowledged. Further research could focus on increasing the number of activities, improving the performance of the GRU-based RNN and exploring other neural network architectures to better capture dependencies in the data. Overall, the thesis presents a proof of concept for the detection of ten activities related to a persons’s everyday life. 



#### Bachelor Thesis: An Empirical Study to examine the Relationship between a Leader’s Machiavellianism and the Followers’ pro-Group unethical behaviour
For my bachelor thesis, I conducted an empirical study to analyse the relationship between the leader’s Machiavellianism and the followers’ pro-group unethical behaviour. Also, I investigated whether conscientiousness of the followers moderates this relationship.

Some definitions: Machiavellianism refers to a personality trait that is associated with manipulative behaviour, disregard for moral standards and striving for control and status. Pro-group unethical behaviour refers to a concept where an individual engages in unethical behaviour with the intention to support the group. Finally, conscientiousnes is a dimension of the big five personality traits which are used to measure personality. Conscientious individuals are said to be organised, disciplined and tend to adhere by their ethical principles.

For employers, it can be crucial to understand the reasons why employees may engage in unethical behaviour. If companies are able to understand the underlying motivation for unethical behaviour, they have the opportunity to recognise warning signals and prevent scandals.

Using regression analysis, I tested the hypotheses on data from 115 participants. I found no support for either hypothesis. The results are discussed and recommendations for improving the experiment are made. Limitations of the research are that the experimenter could have influenced the participants in ways that were not accounted for. Furthermore, the participants did know know each other before the experiment and the team spirit for each session greatly varied.